# Use Node.js 16 base image
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire application to the container's working directory
COPY . .

# Expose the port that your application runs on
EXPOSE 3000

# Start the React application
CMD ["npm", "start"]
